# Generated by Django 3.2.7 on 2021-09-11 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppraisalForm', '0002_alter_appraisalform_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='appraisalform',
            name='grade',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='appraisalform',
            name='whether_HOD',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='appraisalform',
            name='designation',
            field=models.CharField(choices=[('Assistant Professor', 'Assistant Professor'), ('Associate Professor', 'Associate Professor'), ('Professor', 'Professor')], max_length=200, null=True),
        ),
    ]
