# Generated by Django 3.2.7 on 2021-09-11 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppraisalForm', '0004_auto_20210911_1958'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appraisalform',
            old_name='percent1',
            new_name='percent',
        ),
        migrations.RemoveField(
            model_name='appraisalform',
            name='percent2',
        ),
        migrations.RemoveField(
            model_name='appraisalform',
            name='percent3',
        ),
        migrations.RemoveField(
            model_name='appraisalform',
            name='percent4',
        ),
        migrations.AddField(
            model_name='appraisalform',
            name='c8bfile',
            field=models.FileField(null=True, upload_to='quantitative'),
        ),
    ]
