# Generated by Django 3.2.7 on 2021-09-15 13:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppraisalForm', '0006_auto_20210912_0851'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppraisalForm2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=10, null=True)),
                ('department', models.CharField(choices=[('Basic Science and Humanities', 'Basic Science and Humanities'), ('Mechanical', 'Mechanical'), ('Civil', 'Civil'), ('Computer Science', 'Computer Science'), ('Information Science', 'Information Science'), ('Electronics and Communication', 'Electronics and Communication')], max_length=200, null=True)),
                ('designation', models.CharField(choices=[('Assistant Professor', 'Assistant Professor'), ('Associate Professor', 'Associate Professor'), ('Professor', 'Professor')], max_length=200, null=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('grade', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], max_length=2, null=True)),
                ('whether_HOD', models.BooleanField(default=False)),
                ('submitted_Faculty', models.BooleanField(default=False)),
                ('submitted_HOD', models.BooleanField(default=False)),
                ('submitted_Principal', models.BooleanField(default=False)),
                ('a10_No_of_papers_published_in_journals_score', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(0)])),
                ('a10file', models.FileField(null=True, upload_to='part2')),
                ('a10HOD_score', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(0)])),
                ('a10P_score', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(0)])),
                ('b10_No_of_papers_presented_in_conferences_score', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(0)])),
                ('b10file', models.FileField(null=True, upload_to='part2')),
                ('b10HOD_score', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(0)])),
                ('b10P_score', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(0)])),
                ('c10_No_of_papers_indexed_in_In_Scopus_or_Web_of_Science_or_UGC_care_list_OR_No_of_book_chapters_authored_OR_No_of_Books_Authored_score', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(40), django.core.validators.MinValueValidator(0)])),
                ('c10file', models.FileField(null=True, upload_to='part2')),
                ('c10HOD_score', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(40), django.core.validators.MinValueValidator(0)])),
                ('c10P_score', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(40), django.core.validators.MinValueValidator(0)])),
                ('a11_No_of_Research_Project_proposals_submitted_score', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(0)])),
                ('a11file', models.FileField(null=True, upload_to='part2')),
                ('a11HOD_score', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(0)])),
                ('a11P_score', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(0)])),
                ('b11_No_of_Research_projects_Received_and_Amount_score', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(30), django.core.validators.MinValueValidator(0)])),
                ('b11file', models.FileField(null=True, upload_to='part2')),
                ('b11HOD_score', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(30), django.core.validators.MinValueValidator(0)])),
                ('b11P_score', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(30), django.core.validators.MinValueValidator(0)])),
                ('a12_No_of_Consultancy_projects_received_OR_ongoing_score', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(0)])),
                ('a12file', models.FileField(null=True, upload_to='part2')),
                ('a12HOD_score', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(0)])),
                ('a12P_score', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(0)])),
                ('b12_No_of_patents_applied_awarded_score', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(0)])),
                ('b12file', models.FileField(null=True, upload_to='part2')),
                ('b12HOD_score', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(0)])),
                ('b12P_score', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(0)])),
                ('part2APIscore', models.BigIntegerField(default=0, null=True)),
                ('part2HODAPIscore', models.BigIntegerField(default=0, null=True)),
                ('part2PAPIscore', models.BigIntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AppraisalForm3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=10, null=True)),
                ('department', models.CharField(choices=[('Basic Science and Humanities', 'Basic Science and Humanities'), ('Mechanical', 'Mechanical'), ('Civil', 'Civil'), ('Computer Science', 'Computer Science'), ('Information Science', 'Information Science'), ('Electronics and Communication', 'Electronics and Communication')], max_length=200, null=True)),
                ('designation', models.CharField(choices=[('Assistant Professor', 'Assistant Professor'), ('Associate Professor', 'Associate Professor'), ('Professor', 'Professor')], max_length=200, null=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('grade', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], max_length=2, null=True)),
                ('whether_HOD', models.BooleanField(default=False)),
                ('submitted_Faculty', models.BooleanField(default=False)),
                ('submitted_HOD', models.BooleanField(default=False)),
                ('submitted_Principal', models.BooleanField(default=False)),
                ('a13', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)])),
                ('HOD_a13', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)])),
                ('P_a13', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)])),
                ('b13', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(15), django.core.validators.MinValueValidator(0)])),
                ('HOD_b13', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(15), django.core.validators.MinValueValidator(0)])),
                ('P_b13', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(15), django.core.validators.MinValueValidator(0)])),
                ('c13', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(15), django.core.validators.MinValueValidator(0)])),
                ('HOD_c13', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(15), django.core.validators.MinValueValidator(0)])),
                ('P_c13', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(15), django.core.validators.MinValueValidator(0)])),
                ('d13', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(15), django.core.validators.MinValueValidator(0)])),
                ('HOD_d13', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(15), django.core.validators.MinValueValidator(0)])),
                ('P_d13', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(15), django.core.validators.MinValueValidator(0)])),
                ('e13', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(0)])),
                ('HOD_e13', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(0)])),
                ('P_e13', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(0)])),
                ('f13', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(15), django.core.validators.MinValueValidator(0)])),
                ('HOD_f13', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(15), django.core.validators.MinValueValidator(0)])),
                ('P_f13', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(15), django.core.validators.MinValueValidator(0)])),
                ('a14', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(30), django.core.validators.MinValueValidator(0)])),
                ('HOD_a14', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(30), django.core.validators.MinValueValidator(0)])),
                ('P_a14', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(30), django.core.validators.MinValueValidator(0)])),
                ('b14', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(0)])),
                ('HOD_b14', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(0)])),
                ('P_b14', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(0)])),
                ('c14', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(0)])),
                ('c14file', models.FileField(null=True, upload_to='part3')),
                ('HOD_c14', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(0)])),
                ('P_c14', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(0)])),
                ('a15', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(0)])),
                ('a15file', models.FileField(null=True, upload_to='part3')),
                ('HOD_a15', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(0)])),
                ('P_a15', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(0)])),
                ('part3APIscore', models.BigIntegerField(default=0, null=True)),
                ('part3HODAPIscore', models.BigIntegerField(default=0, null=True)),
                ('part3PAPIscore', models.BigIntegerField(default=0, null=True)),
                ('GrandScore', models.BigIntegerField(default=0, null=True)),
                ('GrandScoreHOD', models.BigIntegerField(default=0, null=True)),
                ('GrandScoreP', models.BigIntegerField(default=0, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='appraisalform',
            name='GrandScore',
        ),
        migrations.RemoveField(
            model_name='appraisalform',
            name='GrandScoreHOD',
        ),
        migrations.RemoveField(
            model_name='appraisalform',
            name='GrandScoreP',
        ),
        migrations.RemoveField(
            model_name='appraisalform',
            name='HOD_a13',
        ),
        migrations.RemoveField(
            model_name='appraisalform',
            name='HOD_a14',
        ),
        migrations.RemoveField(
            model_name='appraisalform',
            name='HOD_a15',
        ),
        migrations.RemoveField(
            model_name='appraisalform',
            name='HOD_b13',
        ),
        migrations.RemoveField(
            model_name='appraisalform',
            name='HOD_b14',
        ),
        migrations.RemoveField(
            model_name='appraisalform',
            name='HOD_c13',
        ),
        migrations.RemoveField(
            model_name='appraisalform',
            name='HOD_c14',
        ),
        migrations.RemoveField(
            model_name='appraisalform',
            name='HOD_d13',
        ),
        migrations.RemoveField(
            model_name='appraisalform',
            name='HOD_e13',
        ),
        migrations.RemoveField(
            model_name='appraisalform',
            name='HOD_f13',
        ),
        migrations.RemoveField(
            model_name='appraisalform',
            name='P_a13',
        ),
        migrations.RemoveField(
            model_name='appraisalform',
            name='P_a14',
        ),
        migrations.RemoveField(
            model_name='appraisalform',
            name='P_a15',
        ),
        migrations.RemoveField(
            model_name='appraisalform',
            name='P_b13',
        ),
        migrations.RemoveField(
            model_name='appraisalform',
            name='P_b14',
        ),
        migrations.RemoveField(
            model_name='appraisalform',
            name='P_c13',
        ),
        migrations.RemoveField(
            model_name='appraisalform',
            name='P_c14',
        ),
        migrations.RemoveField(
            model_name='appraisalform',
            name='P_d13',
        ),
        migrations.RemoveField(
            model_name='appraisalform',
            name='P_e13',
        ),
        migrations.RemoveField(
            model_name='appraisalform',
            name='P_f13',
        ),
        migrations.RemoveField(
            model_name='appraisalform',
            name='a10HOD_score',
        ),
        migrations.RemoveField(
            model_name='appraisalform',
            name='a10P_score',
        ),
        migrations.RemoveField(
            model_name='appraisalform',
            name='a10_No_of_papers_published_in_journals_score',
        ),
        migrations.RemoveField(
            model_name='appraisalform',
            name='a10file',
        ),
        migrations.RemoveField(
            model_name='appraisalform',
            name='a11HOD_score',
        ),
        migrations.RemoveField(
            model_name='appraisalform',
            name='a11P_score',
        ),
        migrations.RemoveField(
            model_name='appraisalform',
            name='a11_No_of_Research_Project_proposals_submitted_score',
        ),
        migrations.RemoveField(
            model_name='appraisalform',
            name='a11file',
        ),
        migrations.RemoveField(
            model_name='appraisalform',
            name='a12HOD_score',
        ),
        migrations.RemoveField(
            model_name='appraisalform',
            name='a12P_score',
        ),
        migrations.RemoveField(
            model_name='appraisalform',
            name='a12_No_of_Consultancy_projects_received_OR_ongoing_score',
        ),
        migrations.RemoveField(
            model_name='appraisalform',
            name='a12file',
        ),
        migrations.RemoveField(
            model_name='appraisalform',
            name='a13',
        ),
        migrations.RemoveField(
            model_name='appraisalform',
            name='a14',
        ),
        migrations.RemoveField(
            model_name='appraisalform',
            name='a15',
        ),
        migrations.RemoveField(
            model_name='appraisalform',
            name='a15file',
        ),
        migrations.RemoveField(
            model_name='appraisalform',
            name='b10HOD_score',
        ),
        migrations.RemoveField(
            model_name='appraisalform',
            name='b10P_score',
        ),
        migrations.RemoveField(
            model_name='appraisalform',
            name='b10_No_of_papers_presented_in_conferences_score',
        ),
        migrations.RemoveField(
            model_name='appraisalform',
            name='b10file',
        ),
        migrations.RemoveField(
            model_name='appraisalform',
            name='b11HOD_score',
        ),
        migrations.RemoveField(
            model_name='appraisalform',
            name='b11P_score',
        ),
        migrations.RemoveField(
            model_name='appraisalform',
            name='b11_No_of_Research_projects_Received_and_Amount_score',
        ),
        migrations.RemoveField(
            model_name='appraisalform',
            name='b11file',
        ),
        migrations.RemoveField(
            model_name='appraisalform',
            name='b12HOD_score',
        ),
        migrations.RemoveField(
            model_name='appraisalform',
            name='b12P_score',
        ),
        migrations.RemoveField(
            model_name='appraisalform',
            name='b12_No_of_patents_applied_awarded_score',
        ),
        migrations.RemoveField(
            model_name='appraisalform',
            name='b12file',
        ),
        migrations.RemoveField(
            model_name='appraisalform',
            name='b13',
        ),
        migrations.RemoveField(
            model_name='appraisalform',
            name='b14',
        ),
        migrations.RemoveField(
            model_name='appraisalform',
            name='c10HOD_score',
        ),
        migrations.RemoveField(
            model_name='appraisalform',
            name='c10P_score',
        ),
        migrations.RemoveField(
            model_name='appraisalform',
            name='c10_No_of_papers_indexed_in_In_Scopus_or_Web_of_Science_or_UGC_care_list_OR_No_of_book_chapters_authored_OR_No_of_Books_Authored_score',
        ),
        migrations.RemoveField(
            model_name='appraisalform',
            name='c10file',
        ),
        migrations.RemoveField(
            model_name='appraisalform',
            name='c13',
        ),
        migrations.RemoveField(
            model_name='appraisalform',
            name='c14',
        ),
        migrations.RemoveField(
            model_name='appraisalform',
            name='c14file',
        ),
        migrations.RemoveField(
            model_name='appraisalform',
            name='d13',
        ),
        migrations.RemoveField(
            model_name='appraisalform',
            name='e13',
        ),
        migrations.RemoveField(
            model_name='appraisalform',
            name='f13',
        ),
        migrations.RemoveField(
            model_name='appraisalform',
            name='part2APIscore',
        ),
        migrations.RemoveField(
            model_name='appraisalform',
            name='part2HODAPIscore',
        ),
        migrations.RemoveField(
            model_name='appraisalform',
            name='part2PAPIscore',
        ),
        migrations.RemoveField(
            model_name='appraisalform',
            name='part3APIscore',
        ),
        migrations.RemoveField(
            model_name='appraisalform',
            name='part3HODAPIscore',
        ),
        migrations.RemoveField(
            model_name='appraisalform',
            name='part3PAPIscore',
        ),
    ]
