# Generated by Django 3.2.7 on 2021-09-16 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppraisalForm', '0010_auto_20210916_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appraisalform',
            name='No_of_students1_hod',
        ),
        migrations.RemoveField(
            model_name='appraisalform',
            name='No_of_students2_hod',
        ),
        migrations.RemoveField(
            model_name='appraisalform',
            name='No_of_students3_hod',
        ),
        migrations.RemoveField(
            model_name='appraisalform',
            name='No_of_students4_hod',
        ),
        migrations.RemoveField(
            model_name='appraisalform',
            name='Sub_code1_hod',
        ),
        migrations.RemoveField(
            model_name='appraisalform',
            name='Sub_code2_hod',
        ),
        migrations.RemoveField(
            model_name='appraisalform',
            name='Sub_code3_hod',
        ),
        migrations.RemoveField(
            model_name='appraisalform',
            name='Sub_code4_hod',
        ),
    ]
