# Generated by Django 3.2.7 on 2021-09-17 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppraisalForm', '0014_datestotrack'),
    ]

    operations = [
        migrations.CreateModel(
            name='EXPDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expdate', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='datestotrack',
            name='expdate',
        ),
    ]
