# Generated by Django 3.2.7 on 2021-09-26 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppraisalForm', '0015_auto_20210917_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='appraisalform',
            name='No_of_students5',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='appraisalform',
            name='No_of_students6',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='appraisalform',
            name='No_of_students7',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='appraisalform',
            name='No_of_students8',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='appraisalform',
            name='Percent_over_605',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='appraisalform',
            name='Percent_over_605_hod',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='appraisalform',
            name='Percent_over_606',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='appraisalform',
            name='Percent_over_606_hod',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='appraisalform',
            name='Percent_over_607',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='appraisalform',
            name='Percent_over_607_hod',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='appraisalform',
            name='Percent_over_608',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='appraisalform',
            name='Percent_over_608_hod',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='appraisalform',
            name='Percentage_of_pass5',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='appraisalform',
            name='Percentage_of_pass5_hod',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='appraisalform',
            name='Percentage_of_pass6',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='appraisalform',
            name='Percentage_of_pass6_hod',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='appraisalform',
            name='Percentage_of_pass7',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='appraisalform',
            name='Percentage_of_pass7_hod',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='appraisalform',
            name='Percentage_of_pass8',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='appraisalform',
            name='Percentage_of_pass8_hod',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='appraisalform',
            name='Sub_code5',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='appraisalform',
            name='Sub_code6',
            field=models.CharField(default=0, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='appraisalform',
            name='Sub_code7',
            field=models.CharField(default=0, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='appraisalform',
            name='Sub_code8',
            field=models.CharField(default=0, max_length=200, null=True),
        ),
    ]
