# Generated by Django 3.2.7 on 2021-09-12 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaldetail',
            name='Previous_Exp',
        ),
        migrations.AddField(
            model_name='personaldetail',
            name='yes_or_no',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
