# Generated by Django 3.2.7 on 2021-09-12 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_auto_20210912_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldetail',
            name='Years_of_Service_at_MITM',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
