# Generated by Django 3.2.7 on 2021-09-12 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0003_alter_personaldetail_years_of_service_at_mitm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaldetail',
            name='yes_or_no',
        ),
    ]
