# Generated by Django 3.2.7 on 2021-09-15 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0004_remove_personaldetail_yes_or_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldetail',
            name='Department',
            field=models.CharField(choices=[('Basic Science and Humanities', 'Basic Science and Humanities'), ('Mechanical', 'Mechanical'), ('Civil', 'Civil'), ('Computer Science', 'Computer Science'), ('Information Science', 'Information Science'), ('Electronics and Communication', 'Electronics and Communication'), ('Management', 'Management')], max_length=200),
        ),
    ]
