# Generated by Django 3.2.7 on 2021-09-15 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0005_alter_personaldetail_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaldetail',
            name='Date_on_which_Acquired',
        ),
        migrations.AddField(
            model_name='personaldetail',
            name='Date_of_joining',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='personaldetail',
            name='Department',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='personaldetail',
            name='If_yes_Number_of_candidates_being_supervised',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='personaldetail',
            name='Present_Designation',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='personaldetail',
            name='total_years',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
