# Generated by Django 3.2.7 on 2021-09-16 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0006_auto_20210915_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldetail',
            name='total_years',
            field=models.IntegerField(null=True),
        ),
    ]
