# Generated by Django 3.2.7 on 2021-09-20 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0011_alter_personaldetail_date_of_joining'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldetail',
            name='Staff_ID',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
