# Generated by Django 3.2.7 on 2021-09-23 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0012_alter_personaldetail_staff_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldetail',
            name='Years_of_Service_at_MITM',
            field=models.CharField(default=0, max_length=10, null=True),
        ),
    ]
